# Generated by Django 4.2.7 on 2023-12-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='postal_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
