# Generated by Django 4.2.7 on 2023-12-14 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0001_initial'),
        ('album', '0003_remove_album_rattings_album_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicians.musician'),
        ),
    ]
