# Generated by Django 4.2.7 on 2023-12-25 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_transaction_account_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='account_type',
            new_name='transaction_type',
        ),
    ]
