# Generated by Django 4.2.7 on 2023-12-25 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_rename_account_type_transaction_transaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='ammount',
            new_name='amount',
        ),
    ]
