# Generated by Django 4.2.7 on 2023-12-25 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useraddress_postal_code_and_more'),
        ('transaction', '0004_rename_ammount_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.userbankaccount'),
        ),
    ]
