# Generated by Django 4.2.7 on 2023-12-11 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_author'),
        ('author', '0002_alter_author_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
